# Generated by Django 3.2.8 on 2021-11-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ssn',
            field=models.CharField(default='sd', max_length=20),
        ),
    ]
