# Generated by Django 3.2.8 on 2021-11-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0002_patient_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ssn',
            field=models.CharField(max_length=20),
        ),
    ]
